# Generated by Django 4.2.30 on 2026-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scheduledmeeting_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
