# Generated by Django 4.2.30 on 2026-07-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='whiteboard_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
